### ISSUE TITLE
Some colors hide comments and other nodes

### ISSUE THREAD

**Issue by RishabhRD** [Mangeshrex/uwu.vim#1]
Attaching screenshot for reference
![uwu](https://user-images.githubusercontent.com/26287448/132131976-2b3f63ff-8f8b-40d6-8e98-16076c75cb1d.png)

For example here: comments can't be seen also, #includes isn't visible and other nodes like namespace names of c++ is not visible.

**Comment by RishabhRD** [comment]
When i say not visible I mean, they just look insignificant in compare to other text and one can easily loose focus on them.....

**Comment by Mangeshrex** [comment]
hmm i got it thats the darker foreground color. btw #include is called a preprocessor right ?

**Comment by RishabhRD** [comment]
> btw #include is called a preprocessor right ? 
Yeah

**Comment by Mangeshrex** [comment]
Can you please check :PlugUpdate if you have any problems now?

**Comment by RishabhRD** [comment]
Now it looks so cool for c++....  thanks for the update....

**Comment by Mangeshrex** [comment]
Welcome ❤️

**Comment by RishabhRD** [comment]
Just a little problem... comments on same line as current editing line is not visible yet....
![comments](https://user-images.githubusercontent.com/26287448/132358168-6f212bbe-a90d-4ef7-819d-9ce2a96d011f.png)

You can see relative line 18 it has text written but not visible

**Comment by Mangeshrex** [comment]
Hmm this is cuz the selected background and comment might be same. Ill update this too. Thanks for letting me. Also can you drop your .vimrc here? Pls

**Comment by RishabhRD** [comment]
I use neovim... so its mixture of .vim and .lua

https://github.com/RishabhRD/archrice contains all my configuration.

colorscheme.lua file has my colorscheme config

**Comment by Mangeshrex** [comment]
Hmm ok
