### ISSUE TITLE
Add support for the simple terminal (ST)

### ISSUE THREAD

**Issue by faizan-20** [Mangeshrex/uwu.vim#10]
**Unable to add colors on my own**
When i try and add the hex colors in the config.h it compiles properly but while launching st it says unable to locate colors

**Desktop :**
 - OS: Arch Linux
 - Browser: firefox
 - Version latest

**Comment by Mangeshrex** [comment]
Can you show me the error?

**Comment by faizan-20** [comment]
This is how i added colors in my st :
         
        /* UwU */

        "#c5c8c9"
 	"#131A1C"
	"#1b2224"
	"#e74c4c"
	"#6bb05d"
	"#e59e67"
	"#53A7BF"
	"#CD69CC"

	"#51a39f"
	"#bcbcbc"
	"#454c4e"
	"#c26f6f"
 	"#8dc776"
 	"#e7ac7e"
 	"#6CBAD1"
 	"#E182E0"

 	"#6db0ad"
 	"#bfbfbf"
            };
when i try to execute st using alacritty, i get this error:
`.suckless/st on  main [!?] ∳ st

could not allocate color '#c5c8c9#131A1C#1b2224#e74c4c#6bb05d#e59e67#53A7BF#CD69CC#51a39f#bcbcbc#454c4e#c26f6f#8dc776#e7ac7e#6CBAD1#E182E0#6db0ad#bfbfbf'`

**Comment by Mangeshrex** [comment]
Ahh damn bruh try using the Xresource patch

**Comment by faizan-20** [comment]
Done, it works with the Xresource patch. Thanks mate

**Comment by Mangeshrex** [comment]
Nice then....welcome
