### ISSUE TITLE
line number is barely visible

### ISSUE THREAD

**Issue by faizan-20** [Mangeshrex/uwu.vim#11]
![uwu](https://user-images.githubusercontent.com/69417253/139542294-4d12ac11-62a2-4de2-bde1-3a0a304b9948.png)
Can you please fix it? thanks

**Comment by Mangeshrex** [comment]
Hmm....yeah I'll update it soon. Btw do you use relative number?

**Comment by faizan-20** [comment]
Yes, i use number and relative number both, maybe that's why

**Comment by Mangeshrex** [comment]
Yeah, maybe but I tried setting both of them 

![Screenshot_20211031-095251~2](https://user-images.githubusercontent.com/82205152/139567903-7c9a9623-b83a-4aee-a59b-09ad5c7af659.png)

You can see this

**Comment by gusfrehse** [comment]
Any updates on this? I was trying to make the line number just like the screenshot on the readme, but I have no idea how theming works in vim.

**Comment by Mangeshrex** [comment]
The screenshot had neovim mate.

**Comment by gusfrehse** [comment]
I am using neovim though, and the line number is barely visible still

**Comment by Mangeshrex** [comment]
Can you please show a screenshot?

**Comment by gusfrehse** [comment]
Here, with ```set number relativenumber```:
![image](https://user-images.githubusercontent.com/32969790/145040265-0e588e1c-c47a-42c9-9713-a67e49e404d3.png)
now only ```set number```
![image](https://user-images.githubusercontent.com/32969790/145040559-70769456-414c-404e-84e9-7fdddb95ad42.png)
and now only ```set relativenumber```
![image](https://user-images.githubusercontent.com/32969790/145040733-0dce0b86-a483-45d6-83f2-67989410b7c1.png)

Seems like it's a relativenumber thing, but only in the current line.

It seems to be the same problem that the person who created the issue had.

Sorry for the delay, kind of forgot to check github notifications...

**Comment by Mangeshrex** [comment]
Uhmm can you please update the plugin? The recent fixes might have fixed this one too
