### ISSUE TITLE
2 white colors are too similar

### ISSUE THREAD

**Issue by TKperson** [Mangeshrex/uwu.vim#12]
I'm trying to make an alacritty theme based off of this one
after I finished, I used [panes](https://github.com/stark/Color-Scripts/blob/master/color-scripts/panes) (the front rectangle are darker color and brighter color for the rectangle in the back). And from the looks of it, the white colors are the only ones that I couldn't clearly differentiate.

![Screenshot 2021-11-25 115049](https://user-images.githubusercontent.com/50115012/143494929-36da844f-8d68-498d-8f8e-d208c0548e16.png)

Suggesting changing one of these 2 colors: s:uwu7_gui or s:uwu15_gui

**Comment by Mangeshrex** [comment]
I have my alacritty config file in assets/ folder. + I have updated the changes you suggested. You can try that
