### ISSUE TITLE
[Suggestion/Bug?] Brighten Selected Line Number Color

### ISSUE THREAD

**Issue by jaredreardon** [Mangeshrex/uwu.vim#16]
As pictured below, the color of the selected line number color appears to be wrong. As seen in the image the selected line's number color is the same as that of unselected lines. The preview screenshot shows these as being white. Also there is what appears to be a bug where if you put "set cursorline" in your vimrc or init.vim, the selected line number will actually become even darker than the unselected line numbers. In most colorschemes this would usually be brighter to distinguish it from other lines. The picture of the bug for when cursorline is set is the second one I put below.

![Dim selected line numbers](https://user-images.githubusercontent.com/67240033/144121534-ee907352-1189-43a2-a50c-d5b3028f16f1.png)

![With cursorline set](https://user-images.githubusercontent.com/67240033/144122146-fee2096b-62db-4c42-85e8-48d32ddd3892.png)

**Comment by Mangeshrex** [comment]
Uhmm....I got your point. The preview image on the repository is of neovim. And in my neovim configuration I configured it properly to look beautiful. I'd soon fix and push the fixed script soon.

**Comment by FrenzyExists** [comment]
![image](https://user-images.githubusercontent.com/47986470/144758053-59ab4c67-1203-47f2-8f60-babdbef5e5d2.png)

Found why, both are the same. The solution is to just change the one with the Nr. If anyone wants both the same color, just make a variable. That's kinda what my own theme does. If you want i could open a PR and add the option of to recolor the number to a brighter color or to just leave it with the same color

**Comment by Mangeshrex** [comment]
Ok sure, if you wanna make a PR.

> Found why, both are the same. The solution is to just change the one with the Nr. If anyone wants both the same color, just make a variable. That's kinda what my own theme does. If you want i could open a PR and add the option of to recolor the number to a brighter color or to just leave it with the same color

**Comment by FrenzyExists** [comment]
@Mangeshrex @jaredreardon I made a pull to fix the issue [here](https://github.com/Mangeshrex/uwu.vim/pull/17)
