### ISSUE TITLE
line 107 - highlighting Visual mode 

### ISSUE THREAD

**Issue by moxitron** [Mangeshrex/uwu.vim#18]
Hi, I started using your scheme today and it's just great! however when I entered Visual Mode it got less Visual :) and tbh I wasn't sure if it was selecting anything! since the guibg color was same as background. I guess that is a design choice not a bug. in case I'm wrong, I used `#424747` for `guibg=".s:uwu0_gui.`

**Comment by moxitron** [comment]
That's exactly what I mean, and it's in fact the selection is not visible at all. I mentioned that the coloring was the same as the background color.

**Comment by moxitron** [comment]
> Uhmm..... do you mean that in visual mode the selection is not much visible?

That's exactly what I mean, and it's in fact the selection is not visible at all. I mentioned that the coloring was the same as the background color

**Comment by Mangeshrex** [comment]
Can you please provide me a screenshot? Cuz I don't see it as very not visible

**Comment by moxitron** [comment]
![issue](https://user-images.githubusercontent.com/70322560/152334576-43e14bcf-96c4-4f28-bc27-4fefe932bae4.png)
![issue_corr](https://user-images.githubusercontent.com/70322560/152334579-df8ba0a0-b96d-4efa-a6bf-252e69d814f4.png)
 in both shots I've selected lines 6-8. In the first one I'm using the original scheme, In the second I made the modification I mentioned above. 
my .vimrc has only one line : 
`colorscheme uwu`
and I didn't install the plugin, I only copied uwu.vim to /usr/share/vim/vim81/colors

**Comment by Mangeshrex** [comment]
from how long did you not update the plugin?
