### ISSUE TITLE
colorcolumn not visible

### ISSUE THREAD

**Issue by RishabhRD** [Mangeshrex/uwu.vim#2]
I use 80 characters colorcolumn and that is not visible:
![uwu](https://user-images.githubusercontent.com/26287448/132132076-223c9721-bf49-4805-acbc-219299b53832.png)

**Comment by Mangeshrex** [comment]
thats because some guys didnt want colorcolumn to show up. so i tried to disable it with setting that fg  as similar to background color. Should i consider a bitt lighter + a bit darker foreground to it ?

**Comment by RishabhRD** [comment]
@Mangeshrex color similar to line numbers would even work because we usually don't focus on colorcolumn much until we cross it so it would be non disturbing and even visible

**Comment by Mangeshrex** [comment]
> @Mangeshrex color similar to line numbers would even work because we usually don't focus on colorcolumn much until we cross it so it would be non disturbing and even visible

Ok I'll add a bit lighter color than the background

**Comment by RishabhRD** [comment]
Still colorcolumn is not visible....

**Comment by Mangeshrex** [comment]
Comments right? Ill push that too. Didn't get time to boot

**Comment by RishabhRD** [comment]
Yeah comments are looking awesome

**Comment by Mangeshrex** [comment]
Updated the changes
