### ISSUE TITLE
Omnicomplete colors are not suitable

### ISSUE THREAD

**Issue by RishabhRD** [Mangeshrex/uwu.vim#3]
The red bg and orange fg really looks bad and should be changed
![uwu](https://user-images.githubusercontent.com/26287448/132132110-4a9ce06e-6c97-48f5-91bf-03ba9ee1c0b3.png)

**Comment by Mangeshrex** [comment]
yup i am gna change i just found that weird cause i never use PMenu much. ill add those changes asap.

**Comment by Mangeshrex** [comment]
Fixed

**Comment by RishabhRD** [comment]
Works like a charm

**Comment by Mangeshrex** [comment]
Thanks for letting me the know issue
