### ISSUE TITLE
fixing the color of colorcolumn

### ISSUE THREAD

**Issue by ps173** [Mangeshrex/uwu.vim#4]
I like to use this particular setting for vim  
`set colorcolum=80`
but currently it looks like this.
![This color coloumn](https://user-images.githubusercontent.com/66195934/133888384-bebb6c11-1a21-460f-b8dd-ae5aafadb556.png)

I don't know if this red color is intentional or not. But it is not really pleasant to look at.

**Comment by Mangeshrex** [comment]
Ahh shit, I forgot about this I'll change this back again
