### ISSUE TITLE
Kitty tab colors

### ISSUE THREAD

**Issue by cedrus-8864** [Mangeshrex/uwu.vim#7]
I love this.
I use kitty and I think you are missing colors for tabs.
I used my own colors for them but I still want see your thinking.
Thank you.

**Comment by Mangeshrex** [comment]
Umm can you show your colors? Cause I haven't used kitty much and know nothing about tabs can you show pls?

**Comment by cedrus-8864** [comment]
Basically, I used your colors.

```
active_tab_foreground   #131A1C
active_tab_background   #c5c8c9
inactive_tab_foreground #c5c8c9
inactive_tab_background #131A1C
```

![alt kitty](https://i.imgur.com/Iexp3ld.png)

**Comment by Mangeshrex** [comment]
o.O I never knew about this feature of kitty surely tonight I'll try to play with it and if i like the tabs I would update my configurations here

**Comment by Mangeshrex** [comment]
@cedrus-8864 http://0x0.st/-gq-.png 

here check this.... I liked it to be in this way else its your wish after all + thanks for letting me know about the tabs feature :D

**Comment by cedrus-8864** [comment]
@Mangeshrex I'll try it for a while. Thank you and have a great night.
